### ISSUE TITLE
[bug] sfpegRelatedListKpisCmp - Master Detail relationships not available in App Builder configuration

### ISSUE THREAD

**Issue by eloscarfr** [pegros/PEG_MISC#3]
**Describe the bug**
Master-Detail relations do not appear in "Related list #" while configuring the component in Lightning App builder. Seems that only  related lists are displayed.

**To Reproduce**
0. Having Objet A and Object B, with a Master-Detail relation (A is master of B, field A__r on Object B)
1. Go to a, Object A record
2. Launch 'Lightning App Builder'
3. Add "SP PEG Related List KPIs" component
4. Click on "Related List #1" picklist
5. Related relation "A__r" does not appear

**Expected behavior**
Related relation "A__r" to appear (like other related lists).

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome

**Comment by pegros** [comment]
Actually, the issue comes from the fact that the relationship names appear with a technical API name rather than a label in the drop down list (e.g. "Account_Children__r"). 
Master Detail related list are properly listed --> no bug.

@eloscarfr please be so kind as to properly set the issue title with component name and issue summary according to the template next time you register one. 🙏

**Comment by eloscarfr** [comment]
Thanks @pegros for the workaround provided. For sure, next time I'll set the proper title following your guidance.
